# Generated by Django 4.1.1 on 2022-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='url',
            field=models.URLField(blank=True, default='www.example.com', null=True, unique=True),
        ),
    ]
